import { TypewriterClass } from "typewriter-effect"

export const TypewriterInit = (typewriter: TypewriterClass, callback: () => void) => {

  const PAUSE_INTERVAL = 1000

  typewriter
    .typeString('love, happiest birthday hahaha.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('i really want to have something for ur birthday,')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('but,')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('i dont have much to give.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('then i thought to myself')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('what do i have as of right now')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('web dev knowledge and skills xd')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('anyways, enough of this')
    .pauseFor(PAUSE_INTERVAL)
    .deleteChars(4)
    .typeString('idk')
    .pauseFor(PAUSE_INTERVAL)
    .deleteChars(3)
    .typeString('letter(?) being about me.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('i dont really have much to say')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('i think')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('idk haha')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('i just wanna thank u for everything.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('everything uve done for this relationship.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('ure the reason we made this far.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('idk if i told u this but,')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('what i loved and will always love about u is')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('u allow me to love, take care, and think abt myself WHILE being committed in this relationship.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('theres not a lot of relationship that allows that.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('ur influence to me did that.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('i am happy, healthy, and contented because of u.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('ure incomparable. really.')
    .pauseFor(2000)
    .deleteAll()
    .typeString('i am hoping for the best for your future,')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('and your wishes may be granted if its His will.')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('happiest birthdays,')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('love,')
    .pauseFor(PAUSE_INTERVAL)
    .deleteAll()
    .typeString('clark')
    .callFunction(callback)
    .start()
}

export default TypewriterInit

